Repository woowa-techcamp-2020/hkb-10, pull requests merged in 2020-07, with the labels that each got.

#13 PR: 해당 월의 일별 지출&수입 내역을 불러오는 api
  back/package.json
  back/src/Server.ts
  back/src/apis/history/getDailyHistories.ts
  back/src/apis/history/getDailyHistoriesDummy.ts
  back/src/apis/history/index.ts
  back/src/apis/index.ts
Labels: api

#14 PR: github에서 사용할 markdown template 설정
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#15 PR: 브라우저 라우팅 코드 추가
  front/src/router/Path.ts
  front/src/router/Router.ts
Labels: routing

#17 Feature/component history
  front/src/components/Component.ts
  front/src/components/History/History.ts
  front/src/components/History/HistoryDay.scss
  front/src/components/History/HistoryDay.ts
  front/src/components/History/HistoryItem.scss
  front/src/components/History/HistoryItem.ts
  front/src/components/History/HistoryList.scss
  front/src/components/History/HistoryList.ts
  front/src/components/History/InputForm.scss
  front/src/components/History/InputForm.ts
  front/src/components/History/history.scss
  front/src/components/History/index.ts
  front/src/components/History/variable.scss
  front/src/components/common/Button.ts
  front/src/components/common/Input.ts
  front/src/components/common/Label.ts
  front/src/components/common/List/Li.ts
  front/src/components/common/List/List.ts
  front/src/components/common/List/index.ts
  front/src/components/common/Select/Option.ts
  front/src/components/common/Select/Select.ts
  front/src/components/common/Select/index.ts
  front/src/components/common/index.ts
  front/src/models/Observable.ts
  front/src/reset.css
Labels: view

#18 PR: 내역 불러오는 api 작성
  back/src/apis/history/getHistories.ts
  back/src/apis/history/getHistoriesDummy.ts
  back/src/apis/history/index.ts
  front/src/components/History/History.ts
  front/src/fetch/getHistories.ts
  front/src/fetch/index.ts
Labels: api, fetch

#19 PR: 캘린더 체크박스 기능
  front/src/components/Calendar/Calendar.scss
  front/src/components/Calendar/Calendar.ts
  front/src/components/Calendar/Checkboxes.scss
  front/src/components/Calendar/Checkboxes.ts
  front/src/components/Calendar/index.ts
  front/src/components/Main/ChangeMonth.scss
  front/src/components/Main/ChangeMonth.ts
  front/src/components/Main/Menu.scss
  front/src/components/Main/Menu.ts
  front/src/models/CalendarCheckboxModel.ts
  front/src/models/RootModel.ts
Labels: view, view-model

#21 PR: 캘린더 컴포넌트에서 날짜별로 금액 계산
  back/src/apis/history/getHistoriesDummy.ts
  front/src/components/History/History.ts
  front/src/components/History/HistoryList.ts
  front/src/fetch/getHistories.ts
Labels: view
